package com.whuthm.gc.user;

import com.whuthm.gc.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class UserController {

    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;

//    @RequestMapping(path = "/v1/users")
//    public @ResponseBody List<User> getUsers() {
//        return userRepository.findAll();
//    }

}
